stages:
  - build
  - test

services:
  - name: selenium/standalone-chrome:122.0
    alias: selenium

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore
    - dotnet build --no-restore --configuration Release
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.nuget/packages/

test:
  stage: test
  needs:
    - build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  variables:
    SELENIUM_REMOTE_URL: "http://selenium:4444/wd/hub"
    TEST_BASE_URL: "http://test:5091"
  script:
    - dotnet test --collect:"XPlat Code Coverage" --logger:"console;verbosity=detailed"
    - dotnet tool install -g dotnet-reportgenerator-globaltool
    - export PATH="$PATH:/root/.dotnet/tools"
    - reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coverage-report" -reporttypes:"Html"
  artifacts:
    when: always
    paths:
      - coverage-report/
    expire_in: 1 week
