stages:
  - build
  - test

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore
    - dotnet build --no-restore --configuration Release
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ~/.nuget/packages/

test:
  stage: test
  needs: []
  image: mcr.microsoft.com/dotnet/sdk:8.0
  before_script:
    - apt-get update && apt-get install -y wget gnupg unzip jq
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /usr/share/keyrings/google-chrome.gpg
    - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
    - apt-get update && apt-get install -y google-chrome-stable

    # Get the version
    - CHROME_VERSION=$(google-chrome-stable --version | grep -oP '\d+\.\d+\.\d+\.\d+')

    # Get the matching chromedriver URL
    - CHROMEDRIVER_URL=$(wget -qO- https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')

    - wget "$CHROMEDRIVER_URL" -O chromedriver-linux64.zip
    - unzip chromedriver-linux64.zip
    - mv chromedriver-linux64/chromedriver /usr/local/bin/
    - chmod +x /usr/local/bin/chromedriver
  script:
    - dotnet test --collect:"XPlat Code Coverage" --logger:"console;verbosity=detailed"
    - dotnet tool install -g dotnet-reportgenerator-globaltool
    - export PATH="$PATH:/root/.dotnet/tools"
    - reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coverage-report" -reporttypes:"Html"
  artifacts:
    when: always
    paths:
      - coverage-report/
    expire_in: 1 week
